# version: '3'
# services:
#   serveur:
#     build:
#       context: ./serveur
#     volumes:
#       - ./serveur/app:/app
#     ports:
#       - "5000:5000"
#     depends_on:
#       - api

#   api:
#     build:
#       context: ./api
#     volumes:
#       - ./api/app:/app
#     ports:
#       - "5001:5001"
#     depends_on:
#       - mongo

#   mongo:
#     image: mongo
#     # restart: always
#     # container_name: mongo
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#     ports:
#       - "27017:27017"
#     # volumes:
#     #   - ./mongo:/data/db







version: '3.8'

services:
  serveur:
    image: python:3.9-slim
    environment:
      - GIT_REPO=https://github.com/yourusername/yourrepo-serveur.git
      - GIT_DIR=/app
    volumes:
      - serveur_data:/app
    working_dir: /app
    command: /bin/bash -c "git clone $GIT_REPO $GIT_DIR && cd $GIT_DIR && pip install --no-cache-dir -r requirements.txt && python app.py"
    ports:
      - "5000:5000"
    depends_on:
      - api

  api:
    image: python:3.9-slim
    environment:
      - GIT_REPO=https://github.com/yourusername/yourrepo-api.git
      - GIT_DIR=/app
    volumes:
      - api_data:/app
    working_dir: /app
    command: /bin/bash -c "git clone $GIT_REPO $GIT_DIR && cd $GIT_DIR && pip install --no-cache-dir -r requirements.txt && python app.py"
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

volumes:
  serveur_data:
  api_data:
