version: '1'

services:
  serveur:
    image: python:3.9-slim
    volumes:
      - api_data:/app:ro
    working_dir: /app
    entrypoint: /bin/bash -c "
      apt-get update && \
      while [ ! -f /app/api_initialized ]; do echo 'Waiting for the api container to finish initialization...'; sleep 5; done && \
      cd INFO0803_Virtualisation/serveur && \
      pip install --no-cache-dir -r requirements.txt && \
      python app/app.py"
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  api:
    image: python:3.9-slim
    volumes:
      - api_data:/app
    working_dir: /app
    entrypoint: /bin/bash -c "
      apt-get update && \
      apt-get install -y git && \
      if [ ! -d INFO0803_Virtualisation ]; then git clone https://github.com/killianDRV/INFO0803_Virtualisation.git; fi && \
      touch api_initialized && \
      cd INFO0803_Virtualisation/api && \
      pip install --no-cache-dir -r requirements.txt && \
      python app/app.py"
    ports:
      - '5001:5001'
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: contact_db
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - api_data:/app:ro
    entrypoint: /bin/bash -c "
      while [ ! -f /app/api_initialized ]; do echo 'Waiting for the api container to finish initialization...'; sleep 5; done && \
      cp /app/INFO0803_Virtualisation/mongo/init-mongo.js /docker-entrypoint-initdb.d/init-mongo.js && \
      docker-entrypoint.sh mongod"
      
volumes:
  api_data:
  mongo_data:
